### ISSUE TITLE
How to run without react.js?

### ISSUE THREAD

**Issue by tomeraz** [css-modules/webpack-demo#1]
Great work, really useful.
I am writing code using webpack+babel but without react.js.
Can you post an example of what are the minimal package needed to use module mode css?

Thanks!

**Comment by markdalgleish** [comment]
What are you using instead of React?

CSS Modules will work with any approach where JavaScript is the source of truth for your markup. That could be Angular or Backbone, or server-rendered templates in Node.

Since CSS Modules fit into the component-driven approach to building UIs, React is arguably the best fit for demonstrating it right now. I might add more demos in the future, but it's not a priority yet.

**Comment by tomeraz** [comment]
We are coding in native javascript using Webpack+Babel ES6.
Our goals are minimalist code we can control, and React ~120K plus code
which we cannot maintain ourselves is a concern.

As I understand it, React is not required when using the style loader.
Do you think your demo would be easier to understand and use if you use
only minimal requirements for it to work?

Thanks for your vision, effort and contribution to modularity!
